export const fieldSection: string;
export const fieldsSection: string;
export const filterButton: string;
export const filterHeader: string;
export const fullPage: string;
export const iconsContainer: string;
export const mainPage: string;
export const optionIcon: string;
export const whiteInput: string;
