export const arrowIcon: string;
export const cardFooter: string;
export const dispatched: string;
export const firstIcon: string;
export const iconContainer: string;
export const inProduction: string;
export const mainIcon: string;
export const orderCard: string;
export const placed: string;
